//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string Nome { get; set; }
        public string Departamento { get; set; }
        public string Modulo { get; set; }
        public Nullable<int> Idade { get; set; }
        public Nullable<int> Honorario { get; set; }
    }
}
